# Generated by Django 4.2.7 on 2023-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_steamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='steamId',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
    ]
